export * from "./unittests/asserts.js";
export * from "./unittests/base64.js";
export type * /* TEST DISABLED */ from "./unittests/builder.js";
export type * /* TEST DISABLED */ from "./unittests/canWatch.js";
export type * /* TEST DISABLED */ from "./unittests/comments.js";
export * from "./unittests/compilerCore.js";
export type * /* TEST DISABLED */ from "./unittests/config/commandLineParsing.js";
export type * /* TEST DISABLED */ from "./unittests/config/configurationExtension.js";
export type * /* TEST DISABLED */ from "./unittests/config/convertCompilerOptionsFromJson.js";
export type * /* TEST DISABLED */ from "./unittests/config/convertTypeAcquisitionFromJson.js";
export type * /* TEST DISABLED */ from "./unittests/config/initializeTSConfig.js";
export type * /* TEST DISABLED */ from "./unittests/config/matchFiles.js";
export type * /* TEST DISABLED */ from "./unittests/config/showConfig.js";
export type * /* TEST DISABLED */ from "./unittests/config/tsconfigParsing.js";
export type * /* TEST DISABLED */ from "./unittests/config/tsconfigParsingWatchOptions.js";
export type * /* TEST DISABLED */ from "./unittests/convertToBase64.js";
export type * /* TEST DISABLED */ from "./unittests/customTransforms.js";
export type * /* TEST DISABLED */ from "./unittests/debugDeprecation.js";
export type * /* TEST DISABLED */ from "./unittests/diagnosticCollection.js";
export * from "./unittests/evaluation/arraySpread.js";
export * from "./unittests/evaluation/asyncArrow.js";
export * from "./unittests/evaluation/asyncGenerator.js";
export * from "./unittests/evaluation/autoAccessors.js";
export * from "./unittests/evaluation/awaiter.js";
export * from "./unittests/evaluation/awaitUsingDeclarations.js";
export * from "./unittests/evaluation/constEnum.js";
export * from "./unittests/evaluation/destructuring.js";
export * from "./unittests/evaluation/esDecorators.js";
export * from "./unittests/evaluation/esDecoratorsMetadata.js";
export * from "./unittests/evaluation/externalModules.js";
export * from "./unittests/evaluation/forAwaitOf.js";
export * from "./unittests/evaluation/forOf.js";
export * from "./unittests/evaluation/generator.js";
export * from "./unittests/evaluation/objectRest.js";
export * from "./unittests/evaluation/optionalCall.js";
export * from "./unittests/evaluation/superInStaticInitializer.js";
export * from "./unittests/evaluation/templateLiteral.js";
export * from "./unittests/evaluation/updateExpressionInModule.js";
export * from "./unittests/evaluation/usingDeclarations.js";
export type * /* TEST DISABLED */ from "./unittests/factory.js";
export type * /* TEST DISABLED */ from "./unittests/incrementalParser.js";
export type * /* TEST DISABLED */ from "./unittests/jsDocParsing.js";
export type * /* TEST DISABLED */ from "./unittests/jsonParserRecovery.js";
export type * /* TEST DISABLED */ from "./unittests/moduleResolution.js";
export type * /* TEST DISABLED */ from "./unittests/parsePseudoBigInt.js";
export type * /* TEST DISABLED */ from "./unittests/paths.js";
export type * /* TEST DISABLED */ from "./unittests/printer.js";
export type * /* TEST DISABLED */ from "./unittests/programApi.js";
export type * /* TEST DISABLED */ from "./unittests/publicApi.js";
export type * /* TEST DISABLED */ from "./unittests/regExpScannerRecovery.js";
export type * /* TEST DISABLED */ from "./unittests/reuseProgramStructure.js";
export type * /* TEST DISABLED */ from "./unittests/semver.js";
export type * /* TEST DISABLED */ from "./unittests/services/cancellableLanguageServiceOperations.js";
export type * /* TEST DISABLED */ from "./unittests/services/colorization.js";
export type * /* TEST DISABLED */ from "./unittests/services/convertToAsyncFunction.js";
export type * /* TEST DISABLED */ from "./unittests/services/documentRegistry.js";
export type * /* TEST DISABLED */ from "./unittests/services/extract/constants.js";
export type * /* TEST DISABLED */ from "./unittests/services/extract/functions.js";
export type * /* TEST DISABLED */ from "./unittests/services/extract/ranges.js";
export type * /* TEST DISABLED */ from "./unittests/services/extract/symbolWalker.js";
export type * /* TEST DISABLED */ from "./unittests/services/hostNewLineSupport.js";
export type * /* TEST DISABLED */ from "./unittests/services/languageService.js";
export type * /* TEST DISABLED */ from "./unittests/services/organizeImports.js";
export type * /* TEST DISABLED */ from "./unittests/services/patternMatcher.js";
export type * /* TEST DISABLED */ from "./unittests/services/preProcessFile.js";
export type * /* TEST DISABLED */ from "./unittests/services/textChanges.js";
export type * /* TEST DISABLED */ from "./unittests/services/transpile.js";
export type * /* TEST DISABLED */ from "./unittests/services/utilities.js";
export type * /* TEST DISABLED */ from "./unittests/skipJSDocParsing.js";
export type * /* TEST DISABLED */ from "./unittests/sys/symlinkWatching.js";
export type * /* TEST DISABLED */ from "./unittests/transform.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/amdModulesWithOut.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/clean.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/commandLine.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/configFileErrors.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/configFileExtends.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/containerOnlyReferenced.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/declarationEmit.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/demo.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/emitDeclarationOnly.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/emptyFiles.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/exitCodeOnBogusFile.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/extends.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/fileDelete.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/graphOrdering.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/inferredTypeFromTransitiveModule.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/javascriptProjectEmit.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/lateBoundSymbol.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/libraryResolution.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/moduleResolution.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/moduleSpecifiers.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/noCheck.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/noEmit.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/noEmitOnError.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/outFile.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/outputPaths.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/publicApi.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/referencesWithRootDirInParent.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/resolveJsonModule.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/roots.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/sample.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuild/transitiveReferences.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/configFileErrors.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/demo.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/extends.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/libraryResolution.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/moduleResolution.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/noEmit.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/noEmitOnError.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/programUpdates.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/projectsBuilding.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/publicApi.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/reexport.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/roots.js";
export type * /* TEST DISABLED */ from "./unittests/tsbuildWatch/watchEnvironment.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/cancellationToken.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/commandLine.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/composite.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/declarationEmit.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/extends.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/forceConsistentCasingInFileNames.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/incremental.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/libraryResolution.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/listFilesOnly.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/moduleResolution.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/noCheck.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/noEmit.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/noEmitOnError.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/projectReferences.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/projectReferencesConfig.js";
export type * /* TEST DISABLED */ from "./unittests/tsc/redirect.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/consoleClearing.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/emit.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/emitAndErrorUpdates.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/extends.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/forceConsistentCasingInFileNames.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/incremental.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/libraryResolution.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/listFilesOnly.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/moduleResolution.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/nodeNextWatch.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/noEmit.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/noEmitOnError.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/programUpdates.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/projectsWithReferences.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/resolutionCache.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/resolveJsonModuleWithIncremental.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/sourceOfProjectReferenceRedirect.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/symlinks.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/watchApi.js";
export type * /* TEST DISABLED */ from "./unittests/tscWatch/watchEnvironment.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/applyChangesToOpenFiles.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/autoImportProvider.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/auxiliaryProject.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/cachingFileSystemInformation.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/cancellationToken.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/codeFix.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/compileOnSave.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/completions.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/completionsIncomplete.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/configFileSearch.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/configuredProjects.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/declarationFileMaps.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/documentRegistry.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/duplicatePackages.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/dynamicFiles.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/events/largeFileReferenced.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/events/projectLanguageServiceState.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/events/projectLoading.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/events/projectUpdatedInBackground.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/events/watchEvents.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/exportMapCache.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/extends.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/externalProjects.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/findAllReferences.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/forceConsistentCasingInFileNames.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/formatSettings.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/getApplicableRefactors.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/getEditsForFileRename.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/getExportReferences.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/getFileReferences.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/getMoveToRefactoringFileSuggestions.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/goToDefinition.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/importHelpers.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/inconsistentErrorInEditor.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/inferredProjects.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/inlayHints.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/jsdocTag.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/languageService.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/libraryResolution.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/maxNodeModuleJsDepth.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/metadataInResponse.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/moduleResolution.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/moduleSpecifierCache.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/navTo.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/occurences.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/openFile.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/packageJsonInfo.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/partialSemanticServer.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/pasteEdits.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/plugins.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/pluginsAsync.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/projectErrors.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/projectReferenceCompileOnSave.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/projectReferenceErrors.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/projectReferences.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/projectReferencesSourcemap.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/projectRootFiles.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/projects.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/projectsWithReferences.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/refactors.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/regionDiagnostics.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/reload.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/reloadProjects.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/rename.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/resolutionCache.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/session.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/skipLibCheck.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/smartSelection.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/symlinkCache.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/symLinks.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/syntacticServer.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/syntaxOperations.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/telemetry.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/textStorage.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/typeAquisition.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/typeOnlyImportChains.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/typeReferenceDirectives.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/typingsInstaller.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/versionCache.js";
export type * /* TEST DISABLED */ from "./unittests/tsserver/watchEnvironment.js";
export type * /* TEST DISABLED */ from "./unittests/typeParameterIsPossiblyReferenced.js";
